import pandas as pd
import psp.CopolymerBuilder as cob

# Test
#import os
#from openbabel import openbabel as ob
#obConversion = ob.OBConversion()

#def GetSupportedOutputFormatOB():
#    list_Out_babel = obConversion.GetSupportedOutputFormat()
#    list_babel = []
#    for i in list_Out_babel:
#        list_babel.append(i.split('--')[0].strip())
#    return list_babel

#obConversion.SetInFormat("xyz")
#mol = ob.OBMol()
#path_xyz = 'copolymer_models/test.xyz'
#obConversion.ReadFile(mol, path_xyz)

#list_OB_output = ['gamin', 'XYZHGHG', 'pdb', 'poscar']
#unitname = 'hari'
#output_dir = 'copolymer_models'

#def GenOutputOB(unitname,OBMol,list_OB_output,output_dir):
#    for i in list_OB_output:
#        obConversion.SetOutFormat(i)
#        OBMol.SetTitle("Generated by OpenBabel@PSP -- Output format: "+ i)
#        out_filename = os.path.join(output_dir, unitname+'.'+i)
#        obConversion.WriteFile(OBMol, out_filename)
#        print(i, " DONE ")

#GenOutputOB(unitname,mol,list_OB_output,output_dir)
# End Test
#exit()
df_smiles = pd.read_csv("alternating.csv")

mol = cob.Builder(
    df_smiles,
    ID_col="ID",
    SMILES_col="smiles",
    LeftCap='LeftCap',
    RightCap='RightCap',
    Nunits_col='Nunits',
    Mwt_col='Mwt',
    Copoly_type_col='CopolymerType',
    define_BB_col='define_BB',
    OutDir='copolymer_models',
    NCores=1,
    #Output=['xyz','mol','opls','poscar','gaff','gamin','com'],
    seed=1000
)
results = mol.Build()